# See https://docs.travis-ci.com/user/build-matrix/#using-different-programming-languages-per-job
# TODO add tests for js and python

jobs:
  include:
    - language: python
      python: 3.8
      install:
      - pip install -r scraper/requirements.txt
      script: 
      - pylint scraper/scraper.py

    - language: node_js
      script: 
      - jshint index.js
      - node -e "console.log('Hello from Travis CI')"
