# See https://docs.travis-ci.com/user/build-matrix/#using-different-programming-languages-per-job
# TODO add tests for js and python
services:
  - postgresql

env:
  global:
    - PORT=8080
    
    # https://stackoverflow.com/questions/52586687/set-postgres-database-url-on-travis-ci-for-testing-node-js-application/54206965
    - DB_HOST=127.0.0.1
    - DB_USER=postgres
    - DATABASE_URL=postgres://$DB_USER@$DB_HOST:$PGPORT/ci_test_db

before_script:
  - psql -c 'CREATE DATABASE ci_test_db;' -U postgres

jobs:
  include:
    - language: python
      python: 3.8
      install:
      - pip install -r scraper/requirements.txt
      script: 
      - pylint scraper/scraper.py

    - language: node_js
      node_js: node  # Use the latest stable version of Node
      script: 
      - npm start &  # Run the server in the background
      - npm test
