# TODO add tests for js and python using this strategy:
# https://docs.travis-ci.com/user/build-matrix/#using-different-programming-languages-per-job
language: node_js

script: 
  - jshint index.js
  - node -e "console.log('Hello from Travis CI')"
